☁️ Cloud Nine Theme
FAXES/faxstore-themes pull request #1
Opened 2022-05-10 15:48 UTC by HypnoticSiege

Added a new theme!
I've also added some small documentation for changing and installing themes. (For v2.0 and above when the page is completed and functional).

2022-05-12 12:40 UTC, FAXES requested changes
Looking good <3

One thing, DELETE THAT STUPID APPLE `.DS_Store` FILE 😡😡😡😡😡😡😡😡😡

2022-05-12 12:44 UTC, HypnoticSiege commented
I'M SORRY FAXES LOLL. I gotchu though lmfaooo. I'll just add it to the .gitignore to avoid it in the future as well 😉

2022-05-12 12:45 UTC, HypnoticSiege commented
Done!

2022-05-14 13:14 UTC, FAXES approved these changes

2022-05-14 13:14 UTC, merged